"""lang desc

Revision ID: 4e81f38891ab
Revises: 4b5cd7e1f021
Create Date: 2025-07-27 11:48:52.825416

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4e81f38891ab'
down_revision: Union[str, None] = '4b5cd7e1f021'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('birthdays', sa.Column('lang', sa.Enum('ru', 'en', 'uz', name='langs'), nullable=True))
    op.add_column('birthdays', sa.Column('desc', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('birthdays', 'desc')
    op.drop_column('birthdays', 'lang')
    # ### end Alembic commands ###
